/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalholp3_interface;

import javax.swing.JOptionPane;

/**
 *
 * @author bcrep
 */
public class Interface_9 extends javax.swing.JFrame {

    /**
     * Creates new form Interface_9
     */
    public Interface_9() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBoxJogador1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxJogador2 = new javax.swing.JComboBox<>();
        jLabelResultado = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelVitJogador2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelVitJogador1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("jLabel1");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Desafio 9 - Bruno Crepaldi");

        jComboBoxJogador1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha..", "Pedra", "Papel", "Tesoura" }));

        jLabel2.setText("Jogador 1:");

        jLabel3.setText("Jogador 2:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Pedra - Papel - Tesoura");

        jComboBoxJogador2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha..", "Pedra", "Papel", "Tesoura" }));

        jLabelResultado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel6.setText(" Jogador 2 Vitorias:");

        jLabelVitJogador2.setText("0");

        jLabel8.setText(" Jogador 1 Vitorias:");

        jLabelVitJogador1.setText("0");

        jButton1.setText("Jogar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelResultado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(4, 4, 4)
                        .addComponent(jLabelVitJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelVitJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelVitJogador2)
                    .addComponent(jLabel8)
                    .addComponent(jLabelVitJogador1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String jogador1 = jComboBoxJogador1.getSelectedItem().toString();
        String jogador2 = jComboBoxJogador2.getSelectedItem().toString();
        Integer vitoria1 = Integer.parseInt(jLabelVitJogador1.getText());
        Integer vitoria2 = Integer.parseInt(jLabelVitJogador2.getText());
// EMPATES
        if (jogador1.equals("Pedra") && jogador2.equals("Pedra")) {
            jLabelResultado.setText("Empate");

        } else if (jogador1.equals("Papel") && jogador2.equals("Papel")) {
            jLabelResultado.setText("Empate");

        } else if (jogador1.equals("Tesoura") && jogador2.equals("Tesoura")) {
            jLabelResultado.setText("Empate");

        } // NÃO ESOLHEU NADA 
        else if (jogador1.equals("Escolha..") || jogador2.equals("Escolha")) {
            JOptionPane.showMessageDialog(null, "JOGADA INVALIDA!!!. Selecione Pedra, Papel ou Tesoura para jogar");

        } // PEDRA 1
        else if (jogador1.equals("Pedra") && jogador2.equals("Papel")) {
            jLabelResultado.setText("Vitória Jogador 2");
            vitoria2++;
            jLabelVitJogador2.setText(String.valueOf(vitoria2));

        } else if (jogador1.equals("Pedra") && jogador2.equals("Tesoura")) {
            jLabelResultado.setText("Vitória Jogador 1");
            vitoria1++;
            jLabelVitJogador1.setText(String.valueOf(vitoria1));

        } // PAPEL 1
        else if (jogador1.equals("Papel") && jogador2.equals("Pedra")) {
            jLabelResultado.setText("Vitória Jogador 1");
            vitoria1++;
            jLabelVitJogador1.setText(String.valueOf(vitoria1));

        } else if (jogador1.equals("Papel") && jogador2.equals("Tesoura")) {
            jLabelResultado.setText("Vitória Jogador 2");
            vitoria2++;
            jLabelVitJogador2.setText(String.valueOf(vitoria2));

        }

        //TESOURA 1
        else if (jogador1.equals("Tesoura") && jogador2.equals("Pedra")) {
            jLabelResultado.setText("Vitória Jogador 2");
            vitoria2++;
            jLabelVitJogador2.setText(String.valueOf(vitoria2));

        }else if (jogador1.equals("Tesoura") && jogador2.equals("Papel")) {
            jLabelResultado.setText("Vitória Jogador 1");
            vitoria1++;
            jLabelVitJogador1.setText(String.valueOf(vitoria1));

        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface_9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface_9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface_9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface_9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface_9().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxJogador1;
    private javax.swing.JComboBox<String> jComboBoxJogador2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelResultado;
    private javax.swing.JLabel jLabelVitJogador1;
    private javax.swing.JLabel jLabelVitJogador2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
