/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalholp3_interface;

/**
 *
 * @author bcrep
 */
public class Interface_4 extends javax.swing.JFrame {

    /**
     * Creates new form Interface_4
     */
    public Interface_4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelUF = new javax.swing.JLabel();
        jLabelCapital = new javax.swing.JLabel();
        jLabelPopulacao = new javax.swing.JLabel();
        jLabelImagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Desafio 4 - Bruno Crepaldi");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Estados Brasileiros e Bandeiras");

        jLabel2.setText("Selecione um estado:");

        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um Estado", "Brasil", "Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Distrito Federal", "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Pará", "Paraíba", "Paraná", "Pernambuco", "Piauí", "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do Sul", "Rondônia", "Roraima", "Santa Catarina", "São Paulo", "Sergipe", "Tocantins" }));
        jComboBoxEstado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxEstadoItemStateChanged(evt);
            }
        });
        jComboBoxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstadoActionPerformed(evt);
            }
        });

        jLabel3.setText("UF:");

        jLabel4.setText("Capital:");

        jLabel5.setText("População:");

        jLabelUF.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelUF.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabelCapital.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCapital.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabelPopulacao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPopulacao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(30, 30, 30)
                                    .addComponent(jLabelUF, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelCapital, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelPopulacao, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUF, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelCapital, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelPopulacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)))
                    .addComponent(jLabelImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstadoActionPerformed


    }//GEN-LAST:event_jComboBoxEstadoActionPerformed

    private void jComboBoxEstadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxEstadoItemStateChanged
        String estado = jComboBoxEstado.getSelectedItem().toString();

        String UF = "";
        String capital = "";
        String populacao = "";
        
        if (estado.equals("Brasil")) {
            UF = "BR";
            capital = "Brasilia";
            populacao = "213.317.639 habitantes.";

            String pathImagem = "/imagens/brasil.png";

            jLabelImagem.setIcon(
                    new javax.swing.ImageIcon(getClass().getResource(pathImagem))
            );
        } else if (estado.equals("Acre")) {
            UF = "AC";
            capital = "Rio Branco";
            populacao = "869.265 habitantes.";

            String pathImagem = "/imagens/acre.png";

            jLabelImagem.setIcon(
                    new javax.swing.ImageIcon(getClass().getResource(pathImagem))
            );
        } else if (estado.equals("Alagoas")) {
            UF = "Al";
            capital = "Maceió";
            populacao = "3.322.820 habitantes.";

            String pathImagem = "/imagens/alagoas.png";

            jLabelImagem.setIcon(
                    new javax.swing.ImageIcon(getClass().getResource(pathImagem))
            );
        } else if (estado.equals("Amapá")) {
            UF = "AP";
            capital = "Macapá";
            populacao = "845.731 habitantes.";
            String pathImagem = "/imagens/amapa.png";
            jLabelImagem.setIcon(
                    new javax.swing.ImageIcon(getClass().getResource(pathImagem))
            );
        } else if (estado.equals("Amazonas")) {
            UF = "AM";
            capital = "Manaus";
            populacao = "4.144.597 habitantes.";
            String pathImagem = "/imagens/amazonas.png";
            jLabelImagem.setIcon(
                    new javax.swing.ImageIcon(getClass().getResource(pathImagem))
            );
        } else if (estado.equals("Bahia")) {
            UF = "BA";
            capital = "Salvador";
            populacao = "14.930.634 habitantes.";
            String pathImagem = "/imagens/bahia.png";
            jLabelImagem.setIcon(
                    new javax.swing.ImageIcon(getClass().getResource(pathImagem))
            );
        } else if (estado.equals("Ceará")) {
            UF = "CE";
            capital = "Fortaleza";
            populacao = "9.132.078 habitantes.";
            String pathImagem = "/imagens/ceara.png";
            jLabelImagem.setIcon(
                    new javax.swing.ImageIcon(getClass().getResource(pathImagem))
            );
        } else if (estado.equals("Distrito Federal")) {
            UF = "DF";
            capital = "Brasília";
            populacao = "3.055.149 habitantes.";
            String pathImagem = "/imagens/distrito_federal.png";
            jLabelImagem.setIcon(
                    new javax.swing.ImageIcon(getClass().getResource(pathImagem))
            );
        } else if (estado.equals("Espírito Santo")) {
            UF = "ES";
            capital = "Vitória";
            populacao = "4.064.052 habitantes.";
            String pathImagem = "/imagens/espirito_santo.png";
            jLabelImagem.setIcon(
                    new javax.swing.ImageIcon(getClass().getResource(pathImagem))
            );
        } else if (estado.equals("Goiás")) {
            UF = "GO";
            capital = "Goiânia";
            populacao = "7.113.540 habitantes.";
            String pathImagem = "/imagens/goias.png";
            jLabelImagem.setIcon(
                    new javax.swing.ImageIcon(getClass().getResource(pathImagem))
            );
        } else if (estado.equals("Maranhão")) {
            UF = "MA";
            capital = "São Luís";
            populacao = "7.114.598 habitantes.";
            String pathImagem = "/imagens/maranhao.png";
            jLabelImagem.setIcon(
                    new javax.swing.ImageIcon(getClass().getResource(pathImagem))
            );
        } else if (estado.equals("Mato Grosso")) {
            UF = "MT";
            capital = "Cuiabá";
            populacao = "3.526.220 habitantes.";
            String pathImagem = "/imagens/mato_grosso.png";
            jLabelImagem.setIcon(
                    new javax.swing.ImageIcon(getClass().getResource(pathImagem))
            );
        } else if (estado.equals("Mato Grosso do Sul")) {
            UF = "MS";
            capital = "Campo Grande";
            populacao = "2.809.394 habitantes.";
            String pathImagem = "/imagens/mato_grosso_do_sul.png";
            jLabelImagem.setIcon(
                    new javax.swing.ImageIcon(getClass().getResource(pathImagem))
            );
        } else if (estado.equals("Minas Gerais")) {
            UF = "MG";
            capital = "Belo Horizonte";
            populacao = "21.119.536 habitantes.";
            String pathImagem = "/imagens/minas_gerais.png";
            jLabelImagem.setIcon(
                    new javax.swing.ImageIcon(getClass().getResource(pathImagem))
            );
        } else if (estado.equals("Pará")) {
            UF = "PA";
            capital = "Belém";
            populacao = "8.513.497 habitantes.";
            String pathImagem = "/imagens/para.png";
            jLabelImagem.setIcon(
                    new javax.swing.ImageIcon(getClass().getResource(pathImagem))
            );
        } else if (estado.equals("Paraíba")) {
            UF = "PB";
            capital = "João Pessoa";
            populacao = "3.996.496 habitantes.";
            String pathImagem = "/imagens/paraiba.png";
            jLabelImagem.setIcon(
                    new javax.swing.ImageIcon(getClass().getResource(pathImagem))
            );
        } else if (estado.equals("Paraná")) {
            UF = "PR";
            capital = "Curitiba";
            populacao = "11.348.937 habitantes.";
            String pathImagem = "/imagens/parana.png";
            jLabelImagem.setIcon(
                    new javax.swing.ImageIcon(getClass().getResource(pathImagem))
            );
        } else if (estado.equals("Pernambuco")) {
            UF = "PE";
            capital = "Recife";
            populacao = "9.496.294 habitantes.";
            String pathImagem = "/imagens/pernambuco.png";
            jLabelImagem.setIcon(
                    new javax.swing.ImageIcon(getClass().getResource(pathImagem))
            );
        } else if (estado.equals("Piauí")) {
            UF = "PI";
            capital = "Teresina";
            populacao = "3.264.531 habitantes.";
            String pathImagem = "/imagens/piaui.png";
            jLabelImagem.setIcon(
                    new javax.swing.ImageIcon(getClass().getResource(pathImagem))
            );
        } else if (estado.equals("Rio de Janeiro")) {
            UF = "RJ";
            capital = "Rio de Janeiro";
            populacao = "16.718.956 habitantes.";
            String pathImagem = "/imagens/rio_de_janeiro.png";
            jLabelImagem.setIcon(
                    new javax.swing.ImageIcon(getClass().getResource(pathImagem))
            );
        } else if (estado.equals("Rio Grande do Norte")) {
            UF = "RN";
            capital = "Natal";
            populacao = "3.479.010 habitantes.";
            String pathImagem = "/imagens/rio_grande_do_norte.png";
            jLabelImagem.setIcon(
                    new javax.swing.ImageIcon(getClass().getResource(pathImagem))
            );
        } else if (estado.equals("Rio Grande do Sul")) {
            UF = "RS";
            capital = "Porto Alegre";
            populacao = "11.329.605 habitantes.";
            String pathImagem = "/imagens/rio_grande_do_sul.png";
            jLabelImagem.setIcon(
                    new javax.swing.ImageIcon(getClass().getResource(pathImagem))
            );
        } else if (estado.equals("Rondônia")) {
            UF = "RO";
            capital = "Porto Velho";
            populacao = "1.787.279 habitantes.";
            String pathImagem = "/imagens/rondonia.png";
            jLabelImagem.setIcon(
                    new javax.swing.ImageIcon(getClass().getResource(pathImagem))
            );
        } else if (estado.equals("Roraima")) {
            UF = "RR";
            capital = "Boa Vista";
            populacao = "576.568 habitantes.";
            String pathImagem = "/imagens/roraima.png";
            jLabelImagem.setIcon(
                    new javax.swing.ImageIcon(getClass().getResource(pathImagem))
            );
        } else if (estado.equals("Santa Catarina")) {
            UF = "SC";
            capital = "Florianópolis";
            populacao = "6.910.553 habitantes.";
            String pathImagem = "/imagens/santa_catarina.png";
            jLabelImagem.setIcon(
                    new javax.swing.ImageIcon(getClass().getResource(pathImagem))
            );
        } else if (estado.equals("São Paulo")) {
            UF = "SP";
            capital = "São Paulo";
            populacao = "45.538.936 habitantes.";
            String pathImagem = "/imagens/sao_paulo.png";
            jLabelImagem.setIcon(
                    new javax.swing.ImageIcon(getClass().getResource(pathImagem))
            );
        } else if (estado.equals("Sergipe")) {
            UF = "SE";
            capital = "Aracaju";
            populacao = "2.278.308 habitantes.";
            String pathImagem = "/imagens/sergipe.png";
            jLabelImagem.setIcon(
                    new javax.swing.ImageIcon(getClass().getResource(pathImagem))
            );
        } else if (estado.equals("Tocantins")) {
            UF = "TO";
            capital = "Palmas";
            populacao = "1.555.229 habitantes.";
            String pathImagem = "/imagens/tocantins.png";
            jLabelImagem.setIcon(
                    new javax.swing.ImageIcon(getClass().getResource(pathImagem))
            );
        } else {

        }

        jLabelUF.setText(UF);
        jLabelCapital.setText(capital);
        jLabelPopulacao.setText(populacao);
    }//GEN-LAST:event_jComboBoxEstadoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface_4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCapital;
    private javax.swing.JLabel jLabelImagem;
    private javax.swing.JLabel jLabelPopulacao;
    private javax.swing.JLabel jLabelUF;
    // End of variables declaration//GEN-END:variables
}
