/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacejava;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author bcrep
 */
public class ex4 extends javax.swing.JFrame {

    /**
     * Creates new form ex4
     */
    public ex4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonCandidato1 = new javax.swing.JButton();
        jButtonCandidato2 = new javax.swing.JButton();
        jButtonBranco = new javax.swing.JButton();
        jButtonNulo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelCandidato1 = new javax.swing.JLabel();
        jLabelCandidato2 = new javax.swing.JLabel();
        jLabelBrancos = new javax.swing.JLabel();
        jLabelNulos = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jLabelPerCandidato1 = new javax.swing.JLabel();
        jLabelPerCandidato2 = new javax.swing.JLabel();
        jLabelPerNulos = new javax.swing.JLabel();
        jLabelPerBrancos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Urna Eletrônica");

        jButtonCandidato1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/download.jpg"))); // NOI18N
        jButtonCandidato1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCandidato1ActionPerformed(evt);
            }
        });

        jButtonCandidato2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Traje-Homem-Aranha-Sam-Raimi.png"))); // NOI18N
        jButtonCandidato2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCandidato2ActionPerformed(evt);
            }
        });

        jButtonBranco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonBranco.setText("Branco");
        jButtonBranco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrancoActionPerformed(evt);
            }
        });

        jButtonNulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonNulo.setText("Nulo");
        jButtonNulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuloActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Contagem de Votos:");

        jLabel3.setText("Candidato 1:");

        jLabel4.setText("Candidato 2:");

        jLabel5.setText("Brancos:");

        jLabel6.setText("Nulos:");

        jLabel7.setText("Total de Votos:");

        jLabelCandidato1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCandidato1.setText("0");

        jLabelCandidato2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCandidato2.setText("0");

        jLabelBrancos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelBrancos.setText("0");

        jLabelNulos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNulos.setText("0");

        jLabelTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTotal.setText("0");

        jLabelPerCandidato1.setText("0%");

        jLabelPerCandidato2.setText("0%");

        jLabelPerNulos.setText("0%");

        jLabelPerBrancos.setText("0%");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelCandidato1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel6))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabelCandidato2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                                .addComponent(jLabelBrancos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabelNulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPerBrancos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabelPerCandidato1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                        .addComponent(jLabelPerCandidato2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabelPerNulos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonCandidato1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonBranco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonNulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jButtonCandidato2, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButtonBranco)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonNulo))
                    .addComponent(jButtonCandidato1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCandidato2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelCandidato1)
                    .addComponent(jLabelPerCandidato1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelCandidato2)
                    .addComponent(jLabelPerCandidato2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelBrancos)
                    .addComponent(jLabelPerBrancos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelNulos)
                    .addComponent(jLabelPerNulos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabelTotal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBrancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrancoActionPerformed
        try {
            DecimalFormat df = new DecimalFormat("#,###.00");
            Integer branco = Integer.parseInt(jLabelBrancos.getText());
            Integer total = Integer.parseInt(jLabelTotal.getText());

            jLabelBrancos.setText(String.valueOf(branco + 1));
            jLabelTotal.setText(String.valueOf(total + 1));

            double porcentagem = ((double) (branco + 1) / (total + 1)) * 100;
            String porcentagemFormatada = df.format(porcentagem);

            jLabelPerBrancos.setText(String.valueOf(porcentagemFormatada));

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "É permitido apenas numeros");
        }
    }//GEN-LAST:event_jButtonBrancoActionPerformed

    private void jButtonCandidato1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCandidato1ActionPerformed
        try {
            DecimalFormat df = new DecimalFormat("#,###.00");
            Integer candidato1 = Integer.parseInt(jLabelCandidato1.getText());
            Integer total = Integer.parseInt(jLabelTotal.getText());
            //Double porcentagem  = Double.parseDouble(jLabelPerCandidato1.getText().replaceAll(",", "."));

            jLabelCandidato1.setText(String.valueOf(candidato1 + 1));
            jLabelTotal.setText(String.valueOf(total + 1));

            double porcentagem = ((double) (candidato1 + 1) / (total + 1)) * 100;
            String porcentagemFormatada = df.format(porcentagem);

            jLabelPerCandidato1.setText(String.valueOf(porcentagemFormatada));
            //jLabelPerCandidato1.setText(String.valueOf(total * (candidato1 / 100)));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "É permitido apenas numeros");
        }
    }//GEN-LAST:event_jButtonCandidato1ActionPerformed

    private void jButtonCandidato2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCandidato2ActionPerformed
        try {
            DecimalFormat df = new DecimalFormat("#,###.00");
            Integer candidato2 = Integer.parseInt(jLabelCandidato2.getText());
            Integer total = Integer.parseInt(jLabelTotal.getText());

            jLabelCandidato2.setText(String.valueOf(candidato2 + 1));
            jLabelTotal.setText(String.valueOf(total + 1));

            double porcentagem = ((double) (candidato2 + 1) / (total + 1)) * 100;
            String porcentagemFormatada = df.format(porcentagem);
            
            jLabelPerCandidato2.setText(String.valueOf(porcentagemFormatada));
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "É permitido apenas numeros");
        }
    }//GEN-LAST:event_jButtonCandidato2ActionPerformed

    private void jButtonNuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuloActionPerformed
        try {
            DecimalFormat df = new DecimalFormat("#,###.00");
            Integer nulo = Integer.parseInt(jLabelNulos.getText());
            Integer total = Integer.parseInt(jLabelTotal.getText());

            jLabelNulos.setText(String.valueOf(nulo + 1));
            jLabelTotal.setText(String.valueOf(total + 1));

            double porcentagem = ((double) (nulo + 1) / (total + 1)) * 100;
            String porcentagemFormatada = df.format(porcentagem);
            
            jLabelPerNulos.setText(String.valueOf(porcentagemFormatada));
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "É permitido apenas numeros");
        }
    }//GEN-LAST:event_jButtonNuloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ex4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ex4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ex4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ex4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ex4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBranco;
    private javax.swing.JButton jButtonCandidato1;
    private javax.swing.JButton jButtonCandidato2;
    private javax.swing.JButton jButtonNulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelBrancos;
    private javax.swing.JLabel jLabelCandidato1;
    private javax.swing.JLabel jLabelCandidato2;
    private javax.swing.JLabel jLabelNulos;
    private javax.swing.JLabel jLabelPerBrancos;
    private javax.swing.JLabel jLabelPerCandidato1;
    private javax.swing.JLabel jLabelPerCandidato2;
    private javax.swing.JLabel jLabelPerNulos;
    private javax.swing.JLabel jLabelTotal;
    // End of variables declaration//GEN-END:variables
}
